/**
 * QAntum QA Tool - Configuration Manager
 */

import * as fs from 'fs/promises';
import * as path from 'path';

// ============================================================================
// TYPES
// ============================================================================

export interface QAntumConfig {
  version: string;
  testsDir: string;
  reportsDir: string;
  browser: 'chromium' | 'firefox' | 'webkit';
  headless: boolean;
  timeout: number;
  retries: number;
  parallel: number;
  baseUrl?: string;
  viewport: {
    width: number;
    height: number;
  };
  screenshots: {
    onFailure: boolean;
    fullPage: boolean;
  };
  healing: {
    enabled: boolean;
    autoApply: boolean;
  };
}

// ============================================================================
// DEFAULT CONFIG
// ============================================================================

const DEFAULT_CONFIG: QAntumConfig = {
  version: '1.0.0',
  testsDir: './tests',
  reportsDir: './reports',
  browser: 'chromium',
  headless: true,
  timeout: 30000,
  retries: 1,
  parallel: 1,
  viewport: {
    width: 1280,
    height: 720,
  },
  screenshots: {
    onFailure: true,
    fullPage: false,
  },
  healing: {
    enabled: true,
    autoApply: false,
  },
};

// ============================================================================
// CONFIG MANAGER
// ============================================================================

export class ConfigManager {
  private configPath: string;
  private config: QAntumConfig | null = null;

  constructor(configPath: string = './QAntum.config.json') {
    this.configPath = configPath;
  }

  // --------------------------------------------------------------------------
  // INITIALIZE
  // --------------------------------------------------------------------------

  async initialize(force: boolean = false): Promise<void> {
    // Check if config exists
    const exists = await this.exists();

    if (exists && !force) {
      throw new Error('Configuration already exists. Use --force to overwrite.');
    }

    // Create directories
    await fs.mkdir(DEFAULT_CONFIG.testsDir, { recursive: true });
    await fs.mkdir(DEFAULT_CONFIG.reportsDir, { recursive: true });

    // Write config
    await fs.writeFile(this.configPath, JSON.stringify(DEFAULT_CONFIG, null, 2), 'utf-8');

    // Create example test
    const exampleTest = `/**
 * Example test file
 * Generated by QAntum QA Tool
 */

import { test, expect } from '@playwright/test';

test.describe('Example Tests', () => {
  test('should visit example.com', async ({ page }) => {
    await page.goto('https://example.com');
    await expect(page).toHaveTitle(/Example Domain/);
  });

  test('should have heading', async ({ page }) => {
    await page.goto('https://example.com');
    const heading = page.locator('h1');
    await expect(heading).toHaveText('Example Domain');
  });
});
`;

    await fs.writeFile(path.join(DEFAULT_CONFIG.testsDir, 'example.test.ts'), exampleTest, 'utf-8');
  }

  // --------------------------------------------------------------------------
  // LOAD / SAVE
  // --------------------------------------------------------------------------

  async load(): Promise<QAntumConfig> {
    if (this.config) return this.config;

    try {
      const content = await fs.readFile(this.configPath, 'utf-8');
      this.config = { ...DEFAULT_CONFIG, ...JSON.parse(content) };
      return this.config;
    } catch {
      return DEFAULT_CONFIG;
    }
  }

  async save(config: Partial<QAntumConfig>): Promise<void> {
    const current = await this.load();
    const merged = { ...current, ...config };

    await fs.writeFile(this.configPath, JSON.stringify(merged, null, 2), 'utf-8');

    this.config = merged;
  }

  // --------------------------------------------------------------------------
  // HELPERS
  // --------------------------------------------------------------------------

  async exists(): Promise<boolean> {
    try {
      await fs.access(this.configPath);
      return true;
    } catch {
      return false;
    }
  }

  getDefault(): QAntumConfig {
    return { ...DEFAULT_CONFIG };
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export function createConfigManager(configPath?: string): ConfigManager {
  return new ConfigManager(configPath);
}
